import type { Metadata } from "next";
import {
  LEGAL_UPDATED,
  LegalPage,
  SupportEmailLink,
  type LegalSection,
} from "@/components/legal/legal-page";
import { BRAND } from "@/lib/brand";

export const metadata: Metadata = {
  title: "Terms of Service",
  description: `Terms for using ${BRAND.name}.`,
  alternates: { canonical: "/terms" },
};

const SECTIONS: LegalSection[] = [
  {
    heading: "Using the service",
    body: (
      <p>
        By creating an account or using {BRAND.name} you agree to these terms. If you use it for
        an organization, you confirm you may bind that organization.
      </p>
    ),
  },
  {
    heading: "Accounts",
    body: (
      <p>
        Keep your sign-in details secure. You are responsible for activity under your account.
        Access may be limited to specific email domains and roles set by your administrators.
      </p>
    ),
  },
  {
    heading: "Your data and credentials",
    body: (
      <p>
        You keep ownership of your data, dashboards, rules, and content. You grant us the
        permission needed to process them to run the service. You are responsible for having the
        right to connect the warehouses and AI provider keys you add.
      </p>
    ),
  },
  {
    heading: "AI-generated answers",
    body: (
      <p>
        Answers are generated by AI from your published context and data. They can be wrong or
        incomplete. Review the SQL and context shown with each answer before relying on it for
        important decisions.
      </p>
    ),
  },
  {
    heading: "Acceptable use",
    body: (
      <p>
        Do not misuse the service: no attempts to break security or access other workspaces, no
        unlawful content, no interference with normal operation, and no querying of data you are
        not authorized to access.
      </p>
    ),
  },
  {
    heading: "Availability and changes",
    body: (
      <p>
        We work to keep {BRAND.name} available but do not promise uninterrupted service. Features
        may change, and we may suspend accounts that break these terms.
      </p>
    ),
  },
  {
    heading: "Liability",
    body: (
      <p>
        The service is provided as is, to the extent the law allows. We are not liable for
        indirect or consequential losses, or for decisions made on AI-generated answers.
      </p>
    ),
  },
  {
    heading: "Changes and contact",
    body: (
      <p>
        We may update these terms and will change the date above when we do. Questions:{" "}
        <SupportEmailLink />.
      </p>
    ),
  },
];

export default function TermsPage() {
  return <LegalPage title="Terms of Service" updated={LEGAL_UPDATED} sections={SECTIONS} />;
}
